ALTER TABLE player NOCHECK CONSTRAINT ALL;
ALTER TABLE geography NOCHECK CONSTRAINT ALL;
ALTER TABLE tournament NOCHECK CONSTRAINT ALL;
ALTER TABLE date NOCHECK CONSTRAINT ALL;
ALTER TABLE match NOCHECK CONSTRAINT ALL;
